# Generated by Django 5.0.6 on 2026-06-26 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(help_text='Color hexadecimal para el icono en el mapa, ej: #8B5CF6', max_length=7)),
                ('icono_emoji', models.CharField(default='❓', help_text='Emoji representativo mostrado en el marcador del mapa, ej: 👻', max_length=10)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioVisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(help_text='Nombre público del usuario', max_length=50)),
                ('email', models.EmailField(help_text='Email único por usuario', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario visitante',
                'verbose_name_plural': 'Usuarios visitantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descripcion_corta', models.CharField(help_text='Resumen para el popup del mapa (máx. 500 caracteres)', max_length=500)),
                ('descripcion_larga', models.TextField(help_text='Descripción completa para la ficha del suceso')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('localidad', models.CharField(blank=True, max_length=150)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('comunidad_autonoma', models.CharField(blank=True, max_length=100, verbose_name='Comunidad autónoma')),
                ('fecha_suceso', models.DateField(blank=True, help_text='Fecha aproximada del suceso. Dejar en blanco si es desconocida.', null=True)),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal mostrada en el popup y la ficha', null=True, upload_to='sucesos/portadas/')),
                ('audio_url', models.URLField(blank=True, help_text='URL del audio de psicofonía (MP3, OGG). Ej: https://ejemplo.com/audio.mp3')),
                ('video_url', models.URLField(blank=True, help_text='URL del vídeo (YouTube, Vimeo, etc.)')),
                ('nivel_misterio', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Nivel de misterio editorial del 1 (menor) al 5 (mayor)')),
                ('relevancia', models.IntegerField(default=0, help_text='Puntuación editorial de relevancia. Úsala para portada y destacados. Mayor = más visible.')),
                ('meta_title', models.CharField(blank=True, help_text='Título SEO (máx. 70 chars). Si está vacío se usa el título del suceso.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Descripción SEO (máx. 160 chars). Si está vacía se usa la descripción corta.', max_length=160)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('REVISION', 'En revisión'), ('PUBLICADO', 'Publicado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', help_text='Solo los sucesos en estado PUBLICADO aparecen en el mapa y la API pública.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucesos', to='sucesos.categoria')),
            ],
            options={
                'verbose_name': 'Suceso',
                'verbose_name_plural': 'Sucesos',
                'ordering': ['-relevancia', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagenSuceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de la galería', upload_to='sucesos/galeria/')),
                ('descripcion', models.CharField(blank=True, help_text='Pie de foto / texto alternativo', max_length=300)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en la galería (menor número = primero)')),
                ('suceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='sucesos.suceso')),
            ],
            options={
                'verbose_name': 'Imagen del suceso',
                'verbose_name_plural': 'Imágenes del suceso',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, help_text='Enlace a la fuente (opcional)')),
                ('tipo', models.CharField(choices=[('LIBRO', 'Libro'), ('REVISTA', 'Revista'), ('VIDEO', 'Vídeo'), ('PODCAST', 'Podcast'), ('WEB', 'Web'), ('DOCUMENTAL', 'Documental'), ('OTRO', 'Otro')], default='WEB', max_length=20)),
                ('suceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='sucesos.suceso')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
                'ordering': ['tipo', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('suceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='sucesos.suceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='sucesos.usuariovisitante')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1 estrellas'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Puntuación del 1 al 5')),
                ('fecha', models.DateTimeField(auto_now=True, help_text='Fecha del último voto o actualización')),
                ('suceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='sucesos.suceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='sucesos.usuariovisitante')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='suceso',
            index=models.Index(fields=['estado'], name='sucesos_suc_estado_61fd54_idx'),
        ),
        migrations.AddIndex(
            model_name='suceso',
            index=models.Index(fields=['estado', 'categoria'], name='sucesos_suc_estado_a1fe62_idx'),
        ),
        migrations.AddIndex(
            model_name='suceso',
            index=models.Index(fields=['provincia'], name='sucesos_suc_provinc_d02e56_idx'),
        ),
        migrations.AddIndex(
            model_name='suceso',
            index=models.Index(fields=['slug'], name='sucesos_suc_slug_870304_idx'),
        ),
        migrations.AddIndex(
            model_name='suceso',
            index=models.Index(fields=['-relevancia', '-created_at'], name='sucesos_suc_relevan_e5afb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'suceso')},
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('usuario', 'suceso')},
        ),
    ]
