# Generated by Django 5.0.6 on 2026-06-26 21:47

from django.db import migrations, models


def crear_predicciones_iniciales(apps, schema_editor):
    """Inserta 20 predicciones iniciales para la Calculadora del Destino."""
    PrediccionMuerte = apps.get_model('sucesos', 'PrediccionMuerte')
    
    predicciones = [
        "Te perseguirá una cabra con muy malas intenciones.",
        "Serás absorbido por un agujero negro mientras sacas la basura.",
        "Un fantasma se cansará de que no le hagas caso.",
        "Una invasión de patos extremadamente organizados.",
        "Caerá sobre ti una estantería llena de libros de misterio.",
        "Ganarás una pelea contra un extraterrestre... pero solo durante tres segundos.",
        "Descubrirás que las croquetas también tienen sentimientos.",
        "Un OVNI confundirá tu coche con una zona de aterrizaje.",
        "Un vampiro vegetariano perderá la paciencia contigo.",
        "Un esqueleto del siglo XVIII reclamará tu silla.",
        "Serás traidor accidentalmente por un ejército de hormigas telepáticas.",
        "Las criaturas de la noche decidirán organizar un karaoke en tu casa.",
        "Un poltergeist confundirá tu WiFi con una puerta dimensional.",
        "Te embrujarán por ser demasiado simpático.",
        "Un dragón en miniatura robarará tus calcetines.",
        "Desaparecerás en una reunión de seres de otro planeta.",
        "Un espíritu bromista reorganizará tu cocina.",
        "Serás adoptado por un clan de duendes recolectores.",
        "Una bruja te hechizará para que solo hables en rimas.",
        "Los alienígenas te necesitarán como consultor de moda galáctica.",
    ]
    
    PrediccionMuerte.objects.bulk_create([
        PrediccionMuerte(descripcion=desc, activa=True) for desc in predicciones
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('sucesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionMuerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Predicción humorística del destino. Máx. 255 caracteres.', max_length=255, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Mostrar esta predicción en la Calculadora del Destino')),
            ],
            options={
                'verbose_name': 'Predicción de Muerte',
                'verbose_name_plural': 'Predicciones de Muerte',
                'ordering': ['-id'],
            },
        ),
        migrations.RunPython(crear_predicciones_iniciales),
    ]
